### ISSUE TITLE
Needs Apollo Provider to Render Page for Jest Test

### ISSUE THREAD

**Issue by avuppalapati** [vkapur2202/campus-carpooling#20]
We need Apollo Provider to Render Page for Jest Test. 

1. Go to Application
2. Go to Component
3. Go to User.test.js
4. When you run npm test, the test will fail. 

The test should pass and not show any errors.

 - OS: iOS
 - Browser chrome

![123778990_369549007457232_4931797025181623692_n](https://user-images.githubusercontent.com/59550120/98417769-2c201900-2047-11eb-81ac-4cbbc7732e91.png)

**Comment by sdovgin** [comment]
Fixed by using a different Mocked Provider and updating the mutation mocks from the following website:
https://www.apollographql.com/docs/react/development-testing/testing/#mockedprovider

**Comment by sdovgin** [comment]
Adding the pull request to the issue

**Comment by sdovgin** [comment]
Added the pull request to the issue
